# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\TING\Desktop\pyqt\test.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CamShow(object):
    def setupUi(self, CamShow):
        CamShow.setObjectName("CamShow")
        CamShow.setEnabled(True)
        CamShow.resize(1287, 800)
        CamShow.setMinimumSize(QtCore.QSize(1026, 0))
        CamShow.setMaximumSize(QtCore.QSize(1500, 800))
        self.centralwidget = QtWidgets.QWidget(CamShow)
        self.centralwidget.setObjectName("centralwidget")
        self.ROIFm = QtWidgets.QFrame(self.centralwidget)
        self.ROIFm.setGeometry(QtCore.QRect(20, 410, 521, 281))
        self.ROIFm.setFrameShape(QtWidgets.QFrame.Box)
        self.ROIFm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ROIFm.setObjectName("ROIFm")
        self.DispCopyImg = QtWidgets.QLabel(self.ROIFm)
        self.DispCopyImg.setGeometry(QtCore.QRect(10, 30, 481, 216))
        self.DispCopyImg.setText("")
        self.DispCopyImg.setObjectName("DispCopyImg")
        self.label_7 = QtWidgets.QLabel(self.ROIFm)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 91, 21))
        self.label_7.setStyleSheet("font: 12pt \"Calibri\";")
        self.label_7.setObjectName("label_7")
        self.FullFm = QtWidgets.QFrame(self.centralwidget)
        self.FullFm.setGeometry(QtCore.QRect(20, 10, 521, 391))
        self.FullFm.setStyleSheet("font: 12pt \"Calibri\";")
        self.FullFm.setFrameShape(QtWidgets.QFrame.Box)
        self.FullFm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FullFm.setObjectName("FullFm")
        self.ShowBt = QtWidgets.QPushButton(self.FullFm)
        self.ShowBt.setGeometry(QtCore.QRect(130, 20, 71, 28))
        self.ShowBt.setObjectName("ShowBt")
        self.StopBt = QtWidgets.QPushButton(self.FullFm)
        self.StopBt.setGeometry(QtCore.QRect(210, 20, 111, 28))
        self.StopBt.setObjectName("StopBt")
        self.RecordBt = QtWidgets.QPushButton(self.FullFm)
        self.RecordBt.setGeometry(QtCore.QRect(330, 20, 101, 28))
        self.RecordBt.setObjectName("RecordBt")
        self.DispLb = QtWidgets.QLabel(self.FullFm)
        self.DispLb.setGeometry(QtCore.QRect(20, 100, 481, 261))
        self.DispLb.setText("")
        self.DispLb.setObjectName("DispLb")
        self.FilePathLE = QtWidgets.QLineEdit(self.FullFm)
        self.FilePathLE.setGeometry(QtCore.QRect(80, 50, 371, 31))
        self.FilePathLE.setText("")
        self.FilePathLE.setReadOnly(True)
        self.FilePathLE.setObjectName("FilePathLE")
        self.label_4 = QtWidgets.QLabel(self.FullFm)
        self.label_4.setGeometry(QtCore.QRect(30, 50, 51, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.FullFm)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 121, 20))
        self.label_5.setObjectName("label_5")
        self.FilePathBt = QtWidgets.QToolButton(self.FullFm)
        self.FilePathBt.setGeometry(QtCore.QRect(460, 50, 51, 31))
        self.FilePathBt.setObjectName("FilePathBt")
        self.ExitBt = QtWidgets.QPushButton(self.FullFm)
        self.ExitBt.setGeometry(QtCore.QRect(440, 20, 71, 28))
        self.ExitBt.setObjectName("ExitBt")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(800, 10, 121, 31))
        self.label_8.setStyleSheet("font: 12pt \"Calibri\";")
        self.label_8.setObjectName("label_8")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1100, 380, 41, 21))
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1140, 380, 41, 21))
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1190, 380, 41, 21))
        self.label_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setObjectName("label_3")
        self.Wave = QtWidgets.QFrame(self.centralwidget)
        self.Wave.setGeometry(QtCore.QRect(550, 10, 231, 401))
        self.Wave.setAutoFillBackground(False)
        self.Wave.setStyleSheet("\n"
"border-color: rgb(170, 85, 0);")
        self.Wave.setFrameShape(QtWidgets.QFrame.Box)
        self.Wave.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Wave.setObjectName("Wave")
        self.label_6 = QtWidgets.QLabel(self.Wave)
        self.label_6.setGeometry(QtCore.QRect(20, 70, 31, 21))
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(self.Wave)
        self.label_9.setGeometry(QtCore.QRect(20, 100, 31, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.Wave)
        self.label_10.setGeometry(QtCore.QRect(20, 130, 31, 21))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.Wave)
        self.label_11.setGeometry(QtCore.QRect(20, 160, 31, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.Wave)
        self.label_12.setGeometry(QtCore.QRect(20, 190, 31, 20))
        self.label_12.setObjectName("label_12")
        self.results_window = QtWidgets.QTextEdit(self.Wave)
        self.results_window.setGeometry(QtCore.QRect(10, 270, 201, 121))
        self.results_window.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.results_window.setObjectName("results_window")
        self.label_13 = QtWidgets.QLabel(self.Wave)
        self.label_13.setGeometry(QtCore.QRect(60, 40, 41, 21))
        self.label_13.setStyleSheet("font: 10pt \"Calibri\";\n"
"")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.Wave)
        self.label_14.setGeometry(QtCore.QRect(120, 40, 71, 20))
        self.label_14.setStyleSheet("font: 10pt \"Calibri\";")
        self.label_14.setObjectName("label_14")
        self.BtnGo = QtWidgets.QPushButton(self.Wave)
        self.BtnGo.setGeometry(QtCore.QRect(110, 220, 71, 23))
        self.BtnGo.setStyleSheet("background:rgb(255, 255, 127)")
        self.BtnGo.setObjectName("BtnGo")
        self.label_15 = QtWidgets.QLabel(self.Wave)
        self.label_15.setGeometry(QtCore.QRect(20, 250, 61, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.Wave)
        self.label_16.setGeometry(QtCore.QRect(10, 10, 91, 31))
        self.label_16.setStyleSheet("font: 75 12pt \"Calibri\";")
        self.label_16.setObjectName("label_16")
        self.P1 = QtWidgets.QLineEdit(self.Wave)
        self.P1.setGeometry(QtCore.QRect(50, 70, 61, 22))
        self.P1.setObjectName("P1")
        self.W1 = QtWidgets.QLineEdit(self.Wave)
        self.W1.setGeometry(QtCore.QRect(120, 70, 61, 22))
        self.W1.setObjectName("W1")
        self.W2 = QtWidgets.QLineEdit(self.Wave)
        self.W2.setGeometry(QtCore.QRect(120, 100, 61, 22))
        self.W2.setObjectName("W2")
        self.P2 = QtWidgets.QLineEdit(self.Wave)
        self.P2.setGeometry(QtCore.QRect(50, 100, 61, 22))
        self.P2.setObjectName("P2")
        self.P3 = QtWidgets.QLineEdit(self.Wave)
        self.P3.setGeometry(QtCore.QRect(50, 130, 61, 22))
        self.P3.setObjectName("P3")
        self.W3 = QtWidgets.QLineEdit(self.Wave)
        self.W3.setGeometry(QtCore.QRect(120, 130, 61, 22))
        self.W3.setObjectName("W3")
        self.P4 = QtWidgets.QLineEdit(self.Wave)
        self.P4.setGeometry(QtCore.QRect(50, 160, 61, 22))
        self.P4.setObjectName("P4")
        self.W4 = QtWidgets.QLineEdit(self.Wave)
        self.W4.setGeometry(QtCore.QRect(120, 160, 61, 22))
        self.W4.setObjectName("W4")
        self.P5 = QtWidgets.QLineEdit(self.Wave)
        self.P5.setGeometry(QtCore.QRect(50, 190, 61, 22))
        self.P5.setObjectName("P5")
        self.W5 = QtWidgets.QLineEdit(self.Wave)
        self.W5.setGeometry(QtCore.QRect(120, 190, 61, 22))
        self.W5.setObjectName("W5")
        self.label_18 = QtWidgets.QLabel(self.Wave)
        self.label_18.setGeometry(QtCore.QRect(20, 220, 41, 21))
        self.label_18.setObjectName("label_18")
        self.comboBox = QtWidgets.QComboBox(self.Wave)
        self.comboBox.setGeometry(QtCore.QRect(60, 220, 41, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.graphicsView = PlotWidget(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(550, 450, 241, 241))
        self.graphicsView.setObjectName("graphicsView")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(570, 420, 211, 21))
        self.label_17.setObjectName("label_17")
        self.draw_2 = PlotWidget(self.centralwidget)
        self.draw_2.setGeometry(QtCore.QRect(790, 40, 471, 381))
        self.draw_2.setObjectName("draw_2")
        self.draw_2.raise_()
        self.ROIFm.raise_()
        self.FullFm.raise_()
        self.label_8.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.Wave.raise_()
        self.graphicsView.raise_()
        self.label_17.raise_()
        CamShow.setCentralWidget(self.centralwidget)

        self.retranslateUi(CamShow)
        QtCore.QMetaObject.connectSlotsByName(CamShow)

    def retranslateUi(self, CamShow):
        _translate = QtCore.QCoreApplication.translate
        CamShow.setWindowTitle(_translate("CamShow", "CamShow"))
        self.label_7.setText(_translate("CamShow", "ROI 影像"))
        self.ShowBt.setText(_translate("CamShow", "Start"))
        self.StopBt.setText(_translate("CamShow", "Stop"))
        self.RecordBt.setText(_translate("CamShow", "Save"))
        self.label_4.setText(_translate("CamShow", "路徑:"))
        self.label_5.setText(_translate("CamShow", "及時全影像"))
        self.FilePathBt.setToolTip(_translate("CamShow", "<html><head/><body><p align=\"center\">...</p><p align=\"center\"><br/></p></body></html>"))
        self.FilePathBt.setText(_translate("CamShow", "..."))
        self.ExitBt.setText(_translate("CamShow", "Exit"))
        self.label_8.setText(_translate("CamShow", "垂直強度影像"))
        self.label.setText(_translate("CamShow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ff0000;\">— R: </span></p><p><br/></p><p><span style=\" font-size:10pt;\"><br/></span></p></body></html>"))
        self.label_2.setText(_translate("CamShow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#00ff00;\">— G:</span></p><p><span style=\" font-size:10pt;\"><br/></span></p></body></html>"))
        self.label_3.setText(_translate("CamShow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#0000ff;\">— B:</span></p><p><span style=\" font-size:10pt;\"><br/></span></p></body></html>"))
        self.label_6.setText(_translate("CamShow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">1:</span></p></body></html>"))
        self.label_9.setText(_translate("CamShow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">2:</span></p></body></html>"))
        self.label_10.setText(_translate("CamShow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">3:</span></p></body></html>"))
        self.label_11.setText(_translate("CamShow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">4:</span></p></body></html>"))
        self.label_12.setText(_translate("CamShow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">5:</span></p></body></html>"))
        self.label_13.setText(_translate("CamShow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#0000ff;\">Pixel </span></p></body></html>"))
        self.label_14.setText(_translate("CamShow", "<html><head/><body><p align=\"center\"><span style=\" font-family:\'arial,sans-serif\'; font-size:12pt; font-weight:600; color:#0000ff; background-color:#ffffff;\">λ </span><span style=\" font-size:12pt; font-weight:600; color:#0000ff;\">(nm)</span></p></body></html>"))
        self.BtnGo.setText(_translate("CamShow", "計算校正"))
        self.label_15.setText(_translate("CamShow", "<html><head/><body><p><span style=\" font-weight:600; color:#b37759;\">校正結果</span></p></body></html>"))
        self.label_16.setText(_translate("CamShow", "<html><head/><body><p><span style=\" font-weight:600; color:#550000;\">波長校正</span></p></body></html>"))
        self.label_18.setText(_translate("CamShow", "<html><head/><body><p><span style=\" font-size:9pt; color:#0000ff;\">冪次:</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("CamShow", "1"))
        self.comboBox.setItemText(1, _translate("CamShow", "2"))
        self.comboBox.setItemText(2, _translate("CamShow", "3"))
        self.comboBox.setItemText(3, _translate("CamShow", "4"))
        self.comboBox.setItemText(4, _translate("CamShow", "5"))
        self.label_17.setText(_translate("CamShow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600; color:#aa5500;\">Curve Fitting Plot</span></p></body></html>"))

from pyqtgraph import PlotWidget
