# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\TING\Desktop\pyqt\test.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CamShow(object):
    def setupUi(self, CamShow):
        CamShow.setObjectName("CamShow")
        CamShow.setEnabled(True)
        CamShow.resize(1026, 786)
        CamShow.setMinimumSize(QtCore.QSize(1026, 0))
        CamShow.setMaximumSize(QtCore.QSize(1026, 786))
        self.centralwidget = QtWidgets.QWidget(CamShow)
        self.centralwidget.setObjectName("centralwidget")
        self.ROIFm = QtWidgets.QFrame(self.centralwidget)
        self.ROIFm.setGeometry(QtCore.QRect(20, 410, 521, 271))
        self.ROIFm.setFrameShape(QtWidgets.QFrame.Box)
        self.ROIFm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ROIFm.setObjectName("ROIFm")
        self.DispCopyImg = QtWidgets.QLabel(self.ROIFm)
        self.DispCopyImg.setGeometry(QtCore.QRect(50, 40, 411, 216))
        self.DispCopyImg.setText("")
        self.DispCopyImg.setObjectName("DispCopyImg")
        self.label_7 = QtWidgets.QLabel(self.ROIFm)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 91, 21))
        self.label_7.setStyleSheet("font: 12pt \"Calibri\";")
        self.label_7.setObjectName("label_7")
        self.FullFm = QtWidgets.QFrame(self.centralwidget)
        self.FullFm.setGeometry(QtCore.QRect(20, 10, 521, 381))
        self.FullFm.setStyleSheet("font: 12pt \"Calibri\";")
        self.FullFm.setFrameShape(QtWidgets.QFrame.Box)
        self.FullFm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FullFm.setObjectName("FullFm")
        self.ShowBt = QtWidgets.QPushButton(self.FullFm)
        self.ShowBt.setGeometry(QtCore.QRect(130, 20, 71, 28))
        self.ShowBt.setObjectName("ShowBt")
        self.StopBt = QtWidgets.QPushButton(self.FullFm)
        self.StopBt.setGeometry(QtCore.QRect(210, 20, 111, 28))
        self.StopBt.setObjectName("StopBt")
        self.RecordBt = QtWidgets.QPushButton(self.FullFm)
        self.RecordBt.setGeometry(QtCore.QRect(330, 20, 101, 28))
        self.RecordBt.setObjectName("RecordBt")
        self.DispLb = QtWidgets.QLabel(self.FullFm)
        self.DispLb.setGeometry(QtCore.QRect(50, 100, 411, 261))
        self.DispLb.setText("")
        self.DispLb.setObjectName("DispLb")
        self.FilePathLE = QtWidgets.QLineEdit(self.FullFm)
        self.FilePathLE.setGeometry(QtCore.QRect(80, 50, 371, 31))
        self.FilePathLE.setText("")
        self.FilePathLE.setReadOnly(True)
        self.FilePathLE.setObjectName("FilePathLE")
        self.label_4 = QtWidgets.QLabel(self.FullFm)
        self.label_4.setGeometry(QtCore.QRect(30, 50, 51, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.FullFm)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 121, 20))
        self.label_5.setObjectName("label_5")
        self.FilePathBt = QtWidgets.QToolButton(self.FullFm)
        self.FilePathBt.setGeometry(QtCore.QRect(460, 50, 51, 31))
        self.FilePathBt.setObjectName("FilePathBt")
        self.ExitBt = QtWidgets.QPushButton(self.FullFm)
        self.ExitBt.setGeometry(QtCore.QRect(440, 20, 71, 28))
        self.ExitBt.setObjectName("ExitBt")
        self.btnAdd = QtWidgets.QPushButton(self.centralwidget)
        self.btnAdd.setGeometry(QtCore.QRect(700, 10, 101, 31))
        self.btnAdd.setObjectName("btnAdd")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(560, 10, 141, 31))
        self.label_8.setStyleSheet("font: 12pt \"Calibri\";")
        self.label_8.setObjectName("label_8")
        self.draw_2 = PlotWidget(self.centralwidget)
        self.draw_2.setGeometry(QtCore.QRect(560, 50, 451, 451))
        self.draw_2.setObjectName("draw_2")
        CamShow.setCentralWidget(self.centralwidget)

        self.retranslateUi(CamShow)
        QtCore.QMetaObject.connectSlotsByName(CamShow)

    def retranslateUi(self, CamShow):
        _translate = QtCore.QCoreApplication.translate
        CamShow.setWindowTitle(_translate("CamShow", "CamShow"))
        self.label_7.setText(_translate("CamShow", "ROI 影像"))
        self.ShowBt.setText(_translate("CamShow", "Start"))
        self.StopBt.setText(_translate("CamShow", "Stop"))
        self.RecordBt.setText(_translate("CamShow", "Save"))
        self.label_4.setText(_translate("CamShow", "路徑:"))
        self.label_5.setText(_translate("CamShow", "及時全影像"))
        self.FilePathBt.setToolTip(_translate("CamShow", "<html><head/><body><p align=\"center\">...</p><p align=\"center\"><br/></p></body></html>"))
        self.FilePathBt.setText(_translate("CamShow", "..."))
        self.ExitBt.setText(_translate("CamShow", "Exit"))
        self.btnAdd.setText(_translate("CamShow", "Update Wave"))
        self.label_8.setText(_translate("CamShow", "垂直強度影像"))

from pyqtgraph import PlotWidget
